#!/usr/bin/env bash
# Generates the Obsidian note layer for the OneGRC plan:
#   docs/plan/modules/M-NN.md   one hub note per module
#   docs/plan/slices/SLICE-NN.md one note per slice
#   docs/plan/traceability.md   the crossing matrix
# Regenerate rather than hand-edit. Source data lives beside this script.
set -euo pipefail

GEN="$(cd "$(dirname "$0")" && pwd)"
REPO="$1"
PLAN="$REPO/docs/plan"
STAMP="Generated by Prototype to Product Kit v2.1 · 2026-08-27"

mkdir -p "$PLAN/modules" "$PLAN/slices"

# ---------------------------------------------------------------- lookups ---
declare -A ENAME EMOD MNAME MPURP MWF MDEP MIND MSLICE MENG MDEC MDN MER
declare -A SNUM STITLE SMODS SSCR SENT SDEP SPROVE SSTAT SDEC SDN SER SREAD
declare -A BLOCKS DNHEAD ERHEAD

while IFS='|' read -r id name mod; do
  [ -z "${id:-}" ] && continue
  ENAME[$id]="$name"; EMOD[$id]="$mod"
done < "$GEN/entities.psv"

while IFS='|' read -r id name purp wf dep ind sl eng dec dn er; do
  [ -z "${id:-}" ] && continue
  MNAME[$id]="$name"; MPURP[$id]="$purp"; MWF[$id]="$wf"; MDEP[$id]="$dep"
  MIND[$id]="$ind"; MSLICE[$id]="$sl"; MENG[$id]="$eng"
  MDEC[$id]="$dec"; MDN[$id]="$dn"; MER[$id]="$er"
done < "$GEN/modules.psv"

while IFS='|' read -r num title mods scr ent dep prove stat dec dn er read; do
  [ -z "${num:-}" ] && continue
  STITLE[$num]="$title"; SMODS[$num]="$mods"; SSCR[$num]="$scr"; SENT[$num]="$ent"
  SDEP[$num]="$dep"; SPROVE[$num]="$prove"; SSTAT[$num]="$stat"
  SDEC[$num]="$dec"; SDN[$num]="$dn"; SER[$num]="$er"; SREAD[$num]="$read"
done < "$GEN/slices.psv"

# reverse dependencies
for n in "${!STITLE[@]}"; do
  [ "${SDEP[$n]}" = "n/a" ] && continue
  IFS=',' read -ra ds <<< "${SDEP[$n]}"
  for d in "${ds[@]}"; do BLOCKS[$d]="${BLOCKS[$d]:-} $n"; done
done

# decision-needed and enhancement heading text, for anchor links
while IFS= read -r line; do
  key="${line:5:6}"; DNHEAD[$key]="${line:5}"
done < <(grep -h '^#### DN-' "$REPO/docs/decisions.md")
while IFS= read -r line; do
  key="${line:5:6}"; ERHEAD[$key]="${line:5}"
done < <(grep -h '^#### ER-' "$REPO/docs/decisions.md")

# ---------------------------------------------------------------- helpers ---
elink() { # E-18 -> [[data-model#E-18 Source clause|E-18 Source clause]]
  printf '[[data-model#%s %s|%s %s]]' "$1" "${ENAME[$1]}" "$1" "${ENAME[$1]}"
}
dnlink() { local h="${DNHEAD[$1]:-}"; if [ -z "$h" ]; then echo "MISSING DN key [$1]" >&2; printf "%s" "$1"; else printf "[[decisions#%s|%s]]" "$h" "$1"; fi; }
erlink() { local h="${ERHEAD[$1]:-}"; if [ -z "$h" ]; then echo "MISSING ER key [$1]" >&2; printf "%s" "$1"; else printf "[[decisions#%s|%s]]" "$h" "$1"; fi; }
declink() { printf '[[decisions#Register 1, decisions taken|%s]]' "$1"; }
joinlist() { # list, formatter
  local out="" x; IFS=',' read -ra xs <<< "$1"
  for x in "${xs[@]}"; do
    x="$(echo "$x" | xargs)"; [ -z "$x" ] && continue
    [ -n "$out" ] && out="$out, "
    out="$out$($2 "$x")"
  done
  printf '%s' "$out"
}
# A wikilink alias pipe inside a markdown table cell splits the cell, so every
# link that lands in a table is escaped. Outside tables the links stay plain.
esc() { perl -pe 's/\|/chr(92).chr(124)/ge'; }
plainmod() { printf '[[%s|%s %s]]' "$1" "$1" "${MNAME[$1]}"; }
plainslice() { printf '[[SLICE-%s|SLICE-%s %s]]' "$1" "$1" "${STITLE[$1]}"; }
readlink_() { printf '[[platform#3. Reads|%s]]' "$1"; }
englink() { printf '[[platform#8. One engine per concern|%s]]' "$1"; }

# ------------------------------------------------------------ slice notes ---
for n in $(printf '%s\n' "${!STITLE[@]}" | sort); do
  f="$PLAN/slices/SLICE-$n.md"
  {
    echo "# SLICE-$n ${STITLE[$n]}"
    echo
    echo "$STAMP"
    echo "Last updated: 2026-08-27"
    echo
    echo "> [!info] Generated note"
    echo "> Regenerated from \`docs/plan/slice-plan.md\`. Edit the plan, not this file."
    echo
    echo "| | |"
    echo "|---|---|"
    printf '| **Module** | %s |\n' "$(joinlist "${SMODS[$n]}" plainmod | esc)"
    printf '| **Status** | %s |\n' "${SSTAT[$n]}"
    if [ "${SDEP[$n]}" = "n/a" ]; then
      echo "| **Depends on** | nothing |"
    else
      printf '| **Depends on** | %s |\n' "$(joinlist "${SDEP[$n]}" plainslice | esc)"
    fi
    b="$(printf '%s\n' ${BLOCKS[$n]:-} | sort | tr '\n' ',' | sed 's/,$//')"
    if [ -z "$b" ]; then
      echo "| **Blocks** | nothing |"
    else
      printf '| **Blocks** | %s |\n' "$(joinlist "$b" plainslice | esc)"
    fi
    printf '| **In the plan** | [[slice-plan#5. The slices]] |\n'
    echo
    echo "## Proves"
    echo
    echo "${SPROVE[$n]}."
    echo
    echo "## Builds"
    echo
    printf '**Screens** %s. Full rows in [[screen-inventory#1. Screens]].\n\n' "${SSCR[$n]}"
    if [ "${SENT[$n]}" = "n/a" ]; then
      echo "**Entities** none of its own. This slice reads what other modules own."
    else
      printf '**Entities** %s\n' "$(joinlist "${SENT[$n]}" elink)"
    fi
    echo
    wfs=""
    IFS=',' read -ra ms <<< "${SMODS[$n]}"
    for m in "${ms[@]}"; do
      m="$(echo "$m" | xargs)"
      [ "${MWF[$m]}" = "n/a" ] && continue
      [ -n "$wfs" ] && wfs="$wfs, "
      wfs="$wfs[[${MWF[$m]}|workflows: ${MWF[$m]}]]"
    done
    if [ -n "$wfs" ]; then
      printf '**Workflows** %s\n\n' "$wfs"
    fi
    if [ -n "${SREAD[$n]}" ]; then
      printf '**Reads** %s\n\n' "$(joinlist "${SREAD[$n]}" readlink_)"
    fi
    echo "## Touched by"
    echo
    if [ -n "${SDEC[$n]}" ]; then
      printf '**Decisions taken** %s\n\n' "$(joinlist "${SDEC[$n]}" declink)"
    fi
    if [ -n "${SDN[$n]}" ]; then
      printf '**Decisions needed, blocking** %s\n\n' "$(joinlist "${SDN[$n]}" dnlink)"
    else
      printf '**Decisions needed, blocking** none\n\n'
    fi
    if [ -n "${SER[$n]}" ]; then
      printf '**Enhancements proposed, unbuilt until approved** %s\n\n' "$(joinlist "${SER[$n]}" erlink)"
    else
      printf '**Enhancements proposed** none\n\n'
    fi
    echo "## Close-out"
    echo
    echo "- [ ] Every screen above reads through the seam, never the seed world"
    echo "- [ ] The negative path is demonstrated, with the refusal message stated"
    echo "- [ ] No derived value acquired a column"
    echo "- [ ] Status updated in [[screen-inventory#1. Screens]] and [[slice-plan#5. The slices]]"
    echo "- [ ] Any orphaned prototype file this slice replaced is deleted"
  } > "$f"
done

# ----------------------------------------------------------- module notes ---
for m in $(printf '%s\n' "${!MNAME[@]}" | sort); do
  f="$PLAN/modules/$m.md"
  {
    echo "# $m ${MNAME[$m]}"
    echo
    echo "$STAMP"
    echo "Last updated: 2026-08-27"
    echo
    echo "> [!info] Generated note"
    echo "> Regenerated from \`docs/plan/slice-plan.md\`. Edit the plan, not this file."
    echo
    echo "${MPURP[$m]}."
    echo
    echo "| | |"
    echo "|---|---|"
    if [ "${MWF[$m]}" = "n/a" ]; then
      printf '| **Workflows** | no entity lifecycle of its own |\n'
    else
      printf '| **Workflows** | [[%s\|workflows: %s]] |\n' "${MWF[$m]}" "${MWF[$m]}"
    fi
    case "${MDEP[$m]}" in
      n/a) printf '| **Depends on** | nothing |\n' ;;
      "every module it summarises"|"every module whose sections it composes") printf '| **Depends on** | %s |\n' "${MDEP[$m]}" ;;
      *) printf '| **Depends on** | %s |\n' "$(joinlist "${MDEP[$m]}" plainmod | esc)" ;;
    esac
    case "${MIND[$m]}" in
      nothing) printf '| **Independent of** | nothing, it reads every module |\n' ;;
      "every module") printf '| **Independent of** | every module |\n' ;;
      *) printf '| **Independent of** | %s |\n' "$(joinlist "${MIND[$m]}" plainmod | esc)" ;;
    esac
    printf '| **Slices** | %s |\n' "$(joinlist "${MSLICE[$m]}" plainslice | esc)"
    printf '| **In the plan** | [[slice-plan#2. Modules]], [[screen-inventory#2. Modules]] |\n'
    echo
    echo "## Screens"
    echo
    # Three tables in screen-inventory.md carry different column counts. Find the
    # module column by value, then read the row by the shape that column implies.
    awk -F' *\\| *' -v m="$m" '
      NF > 3 && $2 ~ /^SCR-/ {
        mi = 0
        for (i = 3; i < NF; i++) if ($i ~ /^M-[0-9][0-9] /) { mi = i; break }
        if (mi == 0 || $mi !~ ("^" m " ")) next
        if (mi == 8)                     { surface = $3;                name = $4 }
        else if ($3 ~ /^`/)              { surface = "drawer " $3;      name = $4 }
        else                             { surface = "on many screens"; name = $3 }
        if (!hdr++) { print "| ID | Route or surface | Name shown to user | Status |"; print "|---|---|---|---|" }
        printf "| %s | %s | %s | %s |\n", $2, surface, name, $(NF-1)
      }
      END { if (!hdr) print "None of its own." }
    ' "$PLAN/screen-inventory.md"
    echo
    echo "Full rows, with roles and where each is reached from, in"
    echo "[[screen-inventory#1. Screens]]."
    echo
    echo "## Entities"
    echo
    any=0
    for e in $(printf '%s\n' "${!ENAME[@]}" | sort); do
      [ "${EMOD[$e]}" = "$m" ] || continue
      printf -- '- %s\n' "$(elink "$e")"; any=1
    done
    [ $any -eq 0 ] && echo "None of its own. This module reads what other modules own."
    echo
    echo "## Engines it points at"
    echo
    if [ -n "${MENG[$m]}" ]; then
      printf '%s\n' "$(joinlist "${MENG[$m]}" englink)"
    else
      echo "None."
    fi
    echo
    echo "## Decisions and open questions"
    echo
    if [ -n "${MDEC[$m]}" ]; then
      printf '**Decisions taken** %s\n\n' "$(joinlist "${MDEC[$m]}" declink)"
    fi
    if [ -n "${MDN[$m]}" ]; then
      printf '**Decisions needed** %s\n\n' "$(joinlist "${MDN[$m]}" dnlink)"
    else
      printf '**Decisions needed** none\n\n'
    fi
    if [ -n "${MER[$m]}" ]; then
      printf '**Enhancements proposed, unbuilt until approved** %s\n' "$(joinlist "${MER[$m]}" erlink)"
    else
      printf '**Enhancements proposed** none\n'
    fi
  } > "$f"
done

echo "generated $(ls "$PLAN/slices" | wc -l) slice notes and $(ls "$PLAN/modules" | wc -l) module notes"
