#!/usr/bin/env bash
# Emits docs/plan/traceability.md: one row per crossing, every cell a link.
set -euo pipefail
GEN="$(cd "$(dirname "$0")" && pwd)"
REPO="$1"; PLAN="$REPO/docs/plan"; OUT="$PLAN/traceability.md"

declare -A ENAME EMOD MNAME MWF STITLE SMODS SSCR SENT SDN SER
declare -A SCRNAME SCRMOD SCRSTAT SCRSLICE ENTSLICE DNSLICE ERSLICE DNHEAD ERHEAD

while IFS='|' read -r id name mod; do [ -z "${id:-}" ] && continue
  ENAME[$id]="$name"; EMOD[$id]="$mod"; done < "$GEN/entities.psv"
while IFS='|' read -r id name purp wf dep ind sl eng dec dn er; do [ -z "${id:-}" ] && continue
  MNAME[$id]="$name"; MWF[$id]="$wf"; done < "$GEN/modules.psv"
while IFS='|' read -r num title mods scr ent dep prove stat dec dn er read; do [ -z "${num:-}" ] && continue
  STITLE[$num]="$title"; SMODS[$num]="$mods"; SSCR[$num]="$scr"; SENT[$num]="$ent"
  SDN[$num]="$dn"; SER[$num]="$er"; done < "$GEN/slices.psv"

while IFS= read -r line; do k="${line:5:6}"; DNHEAD[$k]="${line:5}"; done < <(grep -h '^#### DN-' "$REPO/docs/decisions.md")
while IFS= read -r line; do k="${line:5:6}"; ERHEAD[$k]="${line:5}"; done < <(grep -h '^#### ER-' "$REPO/docs/decisions.md")

# screens, from the three tables in the inventory
while IFS='|' read -r id name mod stat; do
  SCRNAME[$id]="$name"; SCRMOD[$id]="$mod"; SCRSTAT[$id]="$stat"
done < <(awk -F' *\\| *' '
  NF > 3 && $2 ~ /^SCR-/ {
    mi = 0; for (i = 3; i < NF; i++) if ($i ~ /^M-[0-9][0-9] /) { mi = i; break }
    if (mi == 0) next
    name = (mi == 8) ? $4 : ($3 ~ /^`/ ? $4 : $3)
    split($mi, mm, " "); printf "%s|%s|%s|%s\n", $2, name, mm[1], $(NF-1)
  }' "$PLAN/screen-inventory.md")

# expand a slice screen cell into ids
expand() {
  local cell="$1" out="" tok a b i
  cell="${cell//,/ }"
  set -- $cell
  while [ $# -gt 0 ]; do
    tok="$1"; shift
    if [ "${1:-}" = "to" ] && [ -n "${2:-}" ]; then
      a="${tok#SCR-}"; b="${2#SCR-}"; shift 2
      for ((i=10#$a; i<=10#$b; i++)); do out="$out SCR-$(printf '%03d' $i)"; done
    elif [[ "$tok" =~ ^(SCR|GAP)- ]]; then
      out="$out $tok"
    fi
  done
  printf '%s' "$out"
}

for n in $(printf '%s\n' "${!STITLE[@]}" | sort); do
  for s in $(expand "${SSCR[$n]}"); do SCRSLICE[$s]="${SCRSLICE[$s]:-}${SCRSLICE[$s]:+, }SLICE-$n"; done
  if [ "${SENT[$n]}" != "n/a" ]; then
    IFS=',' read -ra es <<< "${SENT[$n]}"
    for e in "${es[@]}"; do ENTSLICE[$e]="${ENTSLICE[$e]:-}${ENTSLICE[$e]:+, }SLICE-$n"; done
  fi
  IFS=',' read -ra ds <<< "${SDN[$n]}"; for d in "${ds[@]}"; do [ -n "$d" ] && DNSLICE[$d]="${DNSLICE[$d]:-}${DNSLICE[$d]:+, }SLICE-$n"; done
  IFS=',' read -ra rs <<< "${SER[$n]}"; for r in "${rs[@]}"; do [ -n "$r" ] && ERSLICE[$r]="${ERSLICE[$r]:-}${ERSLICE[$r]:+, }SLICE-$n"; done
done

lk() { local o="" x; case "$1" in *SLICE-*|*M-0*|*E-0*) ;; *) printf "%s" "$1"; return;; esac; for x in $(echo "$1" | tr "," " "); do [ -z "$x" ] && continue; [ -n "$o" ] && o="$o, "; o="$o[[$x]]"; done; printf "%s" "$o"; }

{
cat <<'HEAD'
# Traceability

Generated by Prototype to Product Kit v2.1 · 2026-08-27
Last updated: 2026-08-27

> [!info] Generated note
> Regenerated from the plan documents. Edit the plan, not this file.

Every crossing, in one place: a screen to its entity, its workflow and the slice
that builds it; an entity to the slices that touch it; a slice to what it builds;
an open question to what it blocks. Follow any cell.

Hubs: [[slice-plan]] · [[screen-inventory]] · [[data-model]] · [[workflows]] ·
[[platform]] · [[decisions]]

---

## 1. Screens

A screen with no slice against it is not in the plan and must be raised before it
is built.

| Screen | Name shown to user | Module | Workflows | Built by | Status |
|---|---|---|---|---|---|
HEAD
for s in $(printf '%s\n' "${!SCRNAME[@]}" | sort); do
  m="${SCRMOD[$s]}"; wf="${MWF[$m]:-n/a}"
  wfl="n/a"; [ "$wf" != "n/a" ] && wfl="[[$wf]]"
  printf '| %s | %s | [[%s]] | %s | %s | %s |\n' \
    "$s" "${SCRNAME[$s]}" "$m" "$wfl" "$(lk "${SCRSLICE[$s]:-}")" "${SCRSTAT[$s]}"
done

cat <<'MID'

---

## 2. Entities

| Entity | Module | Workflows | Touched by |
|---|---|---|---|
MID
for e in $(printf '%s\n' "${!ENAME[@]}" | sort); do
  m="${EMOD[$e]}"; wf="${MWF[$m]:-n/a}"; wfl="n/a"; [ "$wf" != "n/a" ] && wfl="[[$wf]]"
  printf '| [[data-model#%s %s\|%s %s]] | [[%s]] | %s | %s |\n' \
    "$e" "${ENAME[$e]}" "$e" "${ENAME[$e]}" "$m" "$wfl" "$(lk "${ENTSLICE[$e]:-}")"
done

cat <<'MID2'

An entity with nothing in the last column is read by the plan and created by no
slice. Every one of those is a gap, not a decision.

---

## 3. Slices

| # | Slice | Module | Screens | Entities |
|---|---|---|---|---|
MID2
for n in $(printf '%s\n' "${!STITLE[@]}" | sort); do
  ents="none"
  if [ "${SENT[$n]}" != "n/a" ]; then
    ents=""; IFS=',' read -ra es <<< "${SENT[$n]}"
    for e in "${es[@]}"; do [ -n "$ents" ] && ents="$ents, "; ents="$ents$e"; done
  fi
  printf '| %s | [[SLICE-%s\|%s]] | %s | %s | %s |\n' \
    "$n" "$n" "${STITLE[$n]}" "$(lk "${SMODS[$n]}")" "${SSCR[$n]}" "$ents"
done

cat <<'MID3'

---

## 4. Open questions, and what they block

Nothing in this table is resolved. Each block is in
[[decisions#Register 2, decisions needed]].

| Question | In one line | Blocks |
|---|---|---|
MID3
for d in $(printf '%s\n' "${!DNHEAD[@]}" | sort); do
  txt="${DNHEAD[$d]#$d }"
  printf '| [[decisions#%s\|%s]] | %s | %s |\n' "${DNHEAD[$d]}" "$d" "$txt" "$(lk "${DNSLICE[$d]:-the whole plan}")"
done

cat <<'MID4'

---

## 5. Enhancements, and where each would land

None of these is built until it is approved. Each block is in
[[decisions#Register 3, enhancement recommendations]].

| Enhancement | In one line | Would land in |
|---|---|---|
MID4
for r in $(printf '%s\n' "${!ERHEAD[@]}" | sort); do
  txt="${ERHEAD[$r]#$r }"
  printf '| [[decisions#%s\|%s]] | %s | %s |\n' "${ERHEAD[$r]}" "$r" "$txt" "$(lk "${ERSLICE[$r]:-}")"
done

cat <<'TAIL'

---

## 6. Modules

| Module | Workflows | Slices |
|---|---|---|
TAIL
for m in $(printf '%s\n' "${!MNAME[@]}" | sort); do
  wf="${MWF[$m]}"; wfl="n/a"; [ "$wf" != "n/a" ] && wfl="[[$wf]]"
  sl=""; for n in $(printf '%s\n' "${!STITLE[@]}" | sort); do
    case ",${SMODS[$n]}," in *",$m,"*) [ -n "$sl" ] && sl="$sl, "; sl="$sl[[SLICE-$n]]";; esac
  done
  printf '| [[%s\|%s %s]] | %s | %s |\n' "$m" "$m" "${MNAME[$m]}" "$wfl" "$sl"
done
} > "$OUT"

echo "wrote $OUT"
